name: hcc_campus_maps
channels:
  - hcc
  - https://conda.anaconda.org/t/HC-83c774c8-94fe-4b2f-b0b2-22cd71073412/hcc
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.4=h06a4308_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mysql-client=9.3.0=he0572af_0
  - mysql-common=9.3.0=h266115a_0
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.12.12=hd63d673_1_cpython
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - dotenv==0.9.9
    - idna==3.11
    - mysql-connector-python==9.4.0
    - numpy==2.0.2
    - pandas==2.3.3
    - pandas-sacct==1.2.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - pytz==2025.2
    - requests==2.32.5
    - six==1.17.0
    - tzdata==2025.2
    - urllib3==2.5.0